coursework02/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace coursework02.Controllers
{
   // [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

coursework02/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using coursework02.Models;
using coursework02.DAL;
using coursework02.ViewModels;

namespace coursework02.Controllers
{
    public class LoansController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Loans
        public ActionResult Index()
        {
            var loans = db.Loans.Include(l => l.Album).Include(l => l.LoanTypes).Include(l => l.Members);
            return View(loans.ToList());
        }

        // GET: Loans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        //6
        // GET: Loans/Create
        public ActionResult Create()
        {
            ViewBag.AlbumId = new SelectList(db.Albums, "id", "Name");
            List<DropDownItem> loanTypes = (from l in db.LoanTypes
                                            select new DropDownItem
                                            {
                                                Name = l.Description + ",Days " + l.Days,
                                                Id = l.Id
                                            }).ToList();
            ViewBag.LoanTypeId = new SelectList(loanTypes, "Id", "Name");
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName");
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Loan loan)
        {
            ViewBag.AlbumId = new SelectList(db.Albums, "id", "Name", loan.AlbumId);
            List<DropDownItem> loanTypes = (from l in db.LoanTypes
                                            select new DropDownItem
                                            {
                                                Name = l.Description + "," + l.Days,
                                                Id = l.Id
                                            }).ToList();
            ViewBag.LoanTypeId = new SelectList(loanTypes, "Id", "Name", loan.LoanTypeId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName", loan.MemberId);
            if (ModelState.IsValid)
            {
                Albums album = db.Albums.Find(loan.AlbumId);
                Member member = db.Members.Include(m=>m.MemberCatagories).FirstOrDefault(m=>m.Id==loan.MemberId);
                int age =(int)(DateTime.Now - member.DateOfBirth).TotalDays/325;
                int maxDVD = member.MemberCatagories.TotalLoan;
                int loanDVD = db.Loans.Any(m => m.MemberId == loan.MemberId && m.ReturnedDate == null) ?
                            db.Loans.Where(m => m.MemberId == loan.MemberId && m.ReturnedDate == null).Count() :
                            0;



                if (loanDVD > maxDVD)
                {
                    ModelState.AddModelError("", "Max Limit Accessed.");
                    return View(loan);
                }

                if ((album.IsAgeBar && age > 18)|| !album.IsAgeBar)
                {
                    loan.TotalAmount = db.LoanTypes.Find(loan.LoanTypeId).Days * db.Albums.Find(loan.AlbumId).FinePerDay;
                    loan.ReturnedDate = null;
                    db.Loans.Add(loan);
                    db.SaveChanges();
                    TempData["Message"] = "Total Amount for Album is " + loan.TotalAmount;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Age Restricted");
                    return View(loan);
                }
               
            }

            
            return View(loan);
        }

        //7
        public ActionResult Return(int? id)
        
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Include(m=>m.Album).FirstOrDefault(m=>m.Id==id.Value);
            if (loan == null)
            {
                return HttpNotFound();
            }
            if (loan.ReturnedDate != null)
            {
                return RedirectToAction("Index");
            }
            string FineAmount = "";
            if (loan.DueDate < DateTime.Now)
            {
                loan.FineAmount = (int)(DateTime.Now - loan.DueDate).TotalDays  * loan.Album.FinePerDay;
                FineAmount = loan.FineAmount.ToString() + " has been Fined.";
            }
            else
            {
                FineAmount = "No Fine Amount.";
            }

            loan.ReturnedDate = DateTime.Now;
            db.SaveChanges();

            TempData["Message"] = "Returned Successfully. "+FineAmount;

            return RedirectToAction("Index");
        }
        
        

        // GET: Loans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlbumId = new SelectList(db.Albums, "id", "Name", loan.AlbumId);
            ViewBag.LoanTypeId = new SelectList(db.LoanTypes, "Id", "Description", loan.LoanTypeId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName", loan.MemberId);
            return View(loan);
        }


        


        // POST: Loans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MemberId,AlbumId,LoanTypeId,IssuedDate,ReturnDate")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AlbumId = new SelectList(db.Albums, "id", "Name", loan.AlbumId);
            ViewBag.LoanTypeId = new SelectList(db.LoanTypes, "Id", "Description", loan.LoanTypeId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName", loan.MemberId);
            return View(loan);
        }

        // GET: Loans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Loan loan = db.Loans.Find(id);
            db.Loans.Remove(loan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

coursework02/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

coursework02/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

coursework02/Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Home Page";
}

<div class="col-md-12">&nbsp;</div>
<div class="jumbotron">
    <h1>Welcome to Everest Video Library</h1>
    <p>Some Text Goes Here. Some Text Goes Here. Some Text Goes Here.</p>
    <div class="row">
        @if (Request.IsAuthenticated)
        {
            <div class="col-md-6">

                <h2>Main Menu</h2>

                <ul class="list-group">
                    <li class="list-group-item">@Html.ActionLink("Artists", "Index", "Artists")</li>
                    <li class="list-group-item">@Html.ActionLink("Producers", "Index", "Producers")</li>
                    <li class="list-group-item">@Html.ActionLink("Album", "Index", "Albums")</li>
                    <li class="list-group-item">@Html.ActionLink("Loan", "Index", "Loans")</li>
                    <li class="list-group-item">@Html.ActionLink("Loan Types", "Index", "LoanTypes")</li>
                    <li class="list-group-item">@Html.ActionLink("Member", "Index", "Members")</li>
                    <li class="list-group-item">@Html.ActionLink("MemberType", "Index", "MemberCategories")</li>
                    <li class="list-group-item">@Html.ActionLink("Search", "Index", "search")</li>

                </ul>

            </div>
            <div class="col-md-6">
                <h2>Search Menu</h2>
                <ul class="list-group">

                    <li class="list-group-item">
                        <a href="@Url.Action("GetAlbumByArtist", "Search")">1.Album By Artist</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GEtAlbumOnShelves", "Search")">2.Album On Shelves</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetLoansByMember", "Search")">3.Loans By Members</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetAlbumsAll", "Search")">4.Album All</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetByCopyNumber", "Search")">5.Album By Copy Number</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("Create", "Loans")">6.Issue Loan</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("Index", "Loans")">7.Return Loan</a>
                    </li>
                   
                    <li class="list-group-item">
                        <a href="@Url.Action("GetMemberDetail", "Search")">8.Member Details</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("Add", "Albums")">9.Add Album</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetAYearOldAlbum", "Search")">10.Get Old Album</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetLoanAlbum", "Search")">11.Loan Albums</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetMemberInActive", "Search")">12.Member Inactive</a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("GetAlbumInActive", "Search")">13.Album InActive</a>
                    </li>
                </ul>
            </div>
        }
    </div>
</div>

@*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@