coursework02/Models/Albums.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace coursework02.Models
{
    public class Albums
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string Name { get; set; }
        public string CopyNumber { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int Length { get; set; }
        public string StudioName { get; set; }
        public bool IsAgeBar { get; set; }
        public decimal FinePerDay { get; set; }
        [NotMapped]
        public HttpPostedFile CoverImage { get; set; }
        public string CoverImagePath { get; set; }
        public  ICollection<Artist> Artists { get; set; } //navigatiion properties
        public  ICollection<Producer> Producers { get; set; } //navigatiion properties

        
    }
}

coursework02/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using coursework02.Models;
using coursework02.DAL;
using coursework02.ViewModels;
using System.IO;

namespace coursework02.Controllers
{
    public class AlbumsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Albums
        public ActionResult Index()
        {
            var albums = db.Albums.Include(m => m.Artists).Include(m => m.Artists).Include(m => m.Producers).OrderBy(m => m.ReleaseDate).ToList();
            //  return View(db.Albums.Include(m=>m.Artists).ToList());
            return View(albums);
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albums albums = db.Albums.Find(id);
            if (albums == null)
            {
                return HttpNotFound();
            }
            return View(albums);
        }

        public ActionResult Add()
        {
            CreateAlbumVM album = new CreateAlbumVM();
            album.ProducerList = new List<ProducerVM>();
            album.ArtistList = new List<ArtistVM>();

            album.Producers = new SelectList(db.Producers.ToList(), "Id", "Name");
            album.Artists = new SelectList(db.Artists.ToList(), "Id", "Name");
            ProducerVM producer = new ProducerVM { Name = "", Studio = "", DateOfBirth = DateTime.Now };
            ArtistVM artist = new ArtistVM { BirthDate = DateTime.Now, Email = "" };
            album.ProducerList.Add(producer);
            album.ArtistList.Add(artist);
            return View(album);
        }
        [HttpPost]
        public ActionResult Add(CreateAlbumVM album, HttpPostedFileBase CoverImage)
        {
            album.Producers = new SelectList(db.Producers.ToList(), "Id", "Name");
            album.Artists = new SelectList(db.Artists.ToList(), "Id", "Name");
            if (ModelState.IsValid)
            {
                List<int> artistIds = album.ArtistIds != null ? album.ArtistIds.ToList() : new List<int>();
                List<int> producerIds = album.ProducerIds != null ? album.ProducerIds.ToList() : new List<int>();

                if (String.IsNullOrEmpty(album.ArtistList[0].Name) && artistIds.Count() == 0)
                {
                    ModelState.AddModelError("", "No Artist Selected");
                    return View(album);
                }

                if (String.IsNullOrEmpty(album.ProducerList[0].Name) && producerIds.Count() == 0)
                {
                    ModelState.AddModelError("", "No Producers Selected");
                    return View(album);
                }

                foreach (var item in album.ArtistList)
                {
                    if (!String.IsNullOrEmpty(item.Name))
                    {
                        Artist artist = new Artist
                        {
                            BirthDate = item.BirthDate,
                            Email = item.Email,
                            Gender = item.Gender,
                            Name = item.Name,
                            PhoneNumber = item.PhoneNumber

                        };
                        if (!db.Artists.Any(m => m.Email == item.Email && m.Name == item.Name))
                        {
                            db.Artists.Add(artist);
                            db.SaveChanges();
                            artistIds.Add(artist.Id);

                        }
                        else
                        {
                            artist = db.Artists.FirstOrDefault(m => m.Email == item.Email && m.Name == item.Name);
                            artistIds.Add(artist.Id);
                        }
                    }
                }



                foreach (var item in album.ProducerList)
                {
                    if (!string.IsNullOrEmpty(item.Name))
                    {
                        Producer producer = new Producer
                        {
                            DateOfBirth = item.DateOfBirth,
                            Name = item.Name,
                            Studio = item.Studio
                        };
                        if (!db.Producers.Any(m => m.DateOfBirth == item.DateOfBirth && m.Name == item.Name && m.Studio == item.Studio))
                        {
                            db.Producers.Add(producer);
                            db.SaveChanges();
                            producerIds.Add(producer.Id);

                        }
                        else
                        {
                            producer = db.Producers.FirstOrDefault(m => m.DateOfBirth == item.DateOfBirth && m.Name == item.Name && m.Studio == item.Studio);
                            producerIds.Add(producer.Id);
                        }
                    }
                }


                if (producerIds.Count() == 0 || artistIds.Count() == 0)
                {
                    ModelState.AddModelError("", "No Artist or Producers");
                    return View(album);
                }

                Albums albums = new Albums
                {
                    Producers = db.Producers.Where(m => producerIds.Contains(m.Id)).ToList(),
                    Artists = db.Artists.Where(m => artistIds.Contains(m.Id)).ToList(),
                    Length = album.Length,
                    Name = album.Name,
                    ReleaseDate = album.ReleaseDate,
                    StudioName = album.StudioName,
                    IsAgeBar = album.IsAgeBar,
                    FinePerDay = album.FinePerDay,
                    CopyNumber = album.CopyNumber,
                    CoverImagePath = "~/Images/Albums/"
                };

                Albums prevAlbum = db.Albums.Include(m => m.Artists).Include(m => m.Producers)
                            .FirstOrDefault(m => m.Name == albums.Name);

                bool Status = db.Albums.Include(m => m.Artists).Include(m => m.Producers)
                            .Any(m => m.Name == albums.Name);

                if (Status)
                {
                    if (albums.Producers.Intersect(prevAlbum.Producers) == null && albums.Artists.Intersect(prevAlbum.Artists) == null)
                    {
                        db.Albums.Add(albums);
                        db.SaveChanges();

                        if (!Directory.Exists(Server.MapPath("~/Images/Albums")))
                        {
                            Directory.CreateDirectory(Server.MapPath("~/Images/Albums"));
                        }

                        if (CoverImage.ContentLength > 0)
                        {
                            CoverImage.SaveAs(Server.MapPath("~/Images/Albums/" + albums.id + ".jpg"));


                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Album Already Exists");
                        return View(album);
                    }

                }
                else
                {
                    db.Albums.Add(albums);
                    db.SaveChanges();

                    if (!Directory.Exists(Server.MapPath("~/Images/Albums")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Images/Albums"));
                    }

                    if (CoverImage.ContentLength > 0)
                    {
                        CoverImage.SaveAs(Server.MapPath("~/Images/Albums/" + albums.id + ".jpg"));


                    }
                    return RedirectToAction("Index");
                }


            }
            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            AlbumVM album = new AlbumVM();
            album.Producers = new SelectList(db.Producers.ToList(), "Id", "Name");
            album.ArtistList = new SelectList(db.Artists.ToList(), "Id", "Name");
            return View(album);
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AlbumVM albums, HttpPostedFileBase CoverImage)
        {
            if (ModelState.IsValid)
            {

                Albums album = new Albums
                {
                    Producers = db.Producers.Where(m => albums.ProducerIds.Contains(m.Id)).ToList(),
                    Artists = db.Artists.Where(m => albums.ArtistIds.Contains(m.Id)).ToList(),
                    Length = albums.Length,
                    Name = albums.Name,
                    ReleaseDate = albums.ReleaseDate,
                    StudioName = albums.StudioName,
                    CoverImagePath = "~/Images/Albums/"
                };
                db.Albums.Add(album);
                db.SaveChanges();

                album = db.Albums.OrderByDescending(m => m.id).FirstOrDefault();


                if (!Directory.Exists(Server.MapPath("~/Images/Albums")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Images/Albums"));
                }

                if (CoverImage.ContentLength > 0)
                {
                    CoverImage.SaveAs(Server.MapPath("~/Images/Albums/" + album.id + ".jpg"));
                }

                return RedirectToAction("Index");
            }
            albums.Producers = new SelectList(db.Producers.ToList(), "Id", "Name");

coursework02/Views/Albums/Add.cshtml
@model coursework02.ViewModels.CreateAlbumVM

@{
    ViewBag.Title = "Add";
}
@using (Html.BeginForm("Add", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Albums</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CopyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CopyNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CopyNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FinePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinePerDay, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                18+
            </label>            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAgeBar)
                @Html.ValidationMessageFor(model => model.IsAgeBar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control", id = "txtReleaseDate" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudioName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudioName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudioName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Cover Image</label>
            <div class="col-md-10">
                <input type="file" name="CoverImage" class="form-control" />

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Producer</label>

            <div class="col-md-10">

                @*@Html.ListBoxFor(x => x.ProducerIds, Model.Producers, new { @class = "form-control" })*@
                @Html.DropDownListFor(x => x.ProducerIds, new SelectList(Model.Producers, "Value", "Text"), new { multiple = "multiple", @class = "form-control", id = "ddlProducer" })

                @Html.ValidationMessageFor(model => model.Producers, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Add Producer</label>
            <div class="col-md-10">
                <table class="table table-bordered" id="tblProducer">
                    <tr>
                        <th>Name</th>
                        <th>Studio</th>
                        <th>DOB</th>
                        <th></th>
                    </tr>
                    @for (int i = 0; i < Model.ProducerList.Count(); i++)
                    {
                        <tr id="dataRow">
                            <td>@Html.TextBoxFor(m => m.ProducerList[i].Name, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ProducerList[i].Studio, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ProducerList[i].DateOfBirth, new { @class = "form-control", id = "txtDOB" })</td>
                            <td>
                                @if (i > 0)
                                {
                                    <a href="#" id="remove">
                                        <i class="fa fa-minus-circle text-danger" style="font-size:15px;"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                    }

                </table>
                <div class="col-md-12 text-right">
                    <a href="#" id="addNew" class="btn btn-default">Add New Row</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Cast Member</label>

            <div class="col-md-10">
                @*  @Html.ListBoxFor(x => x.ArtistIds, Model.Artists, new { @class = "form-control" })*@
                @Html.DropDownListFor(x => x.ArtistIds, new SelectList(Model.Artists, "Value", "Text"), new { multiple = "multiple", @class = "form-control", id = "ddlArtist" })
                @Html.ValidationMessageFor(model => model.ArtistIds, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Add Cast Members</label>
            <div class="col-md-10">
                <table class="table table-bordered" id="tblArtist">
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Gender</th>
                        <th>PhoneNumber</th>
                        <th>DOB</th>
                        <th></th>
                    </tr>
                    @for (int i = 0; i < Model.ArtistList.Count(); i++)
                    {
                        <tr id="dataRow">
                            <td>@Html.TextBoxFor(m => m.ArtistList[i].Name, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ArtistList[i].Email, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ArtistList[i].Gender, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ArtistList[i].PhoneNumber, new { @class = "form-control" })</td>
                            <td>@Html.TextBoxFor(m => m.ArtistList[i].BirthDate, new { @class = "form-control", id = "txtDOB" })</td>
                            <td>
                                @if (i > 0)
                                {
                                    <a href="#" id="remove">
                                        <i class="fa fa-minus-circle text-danger" style="font-size:15px;"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                    }

                </table>
                <div class="col-md-12 text-right">
                    <a href="#" id="addNew" class="btn btn-default">Add New Row</a>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

    <script language="javascript">
        $(document).ready(function () {

           // $("body #txtDOB").datepicker();
            $('body').on('focus', "#txtDOB", function () {
                $(this).datepicker();
            });

            $("#txtReleaseDate").datepicker();

            $('#ddlArtist').select2({
                placeholder: 'Select Artist'
            });

            $('#ddlProducer').select2({
                placeholder: 'Select Producer'
            });

            // 2. Remove
            $('body').on("click", 'a#remove', function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

            //Add new col
            $('body').on("click", 'a#addNew', function (e) {
                e.preventDefault();
                var $tableBody = $(this).parent().parent().find('table');// $("#tblProducer");
                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" id ="remove"><i class="fa fa-minus-circle text-danger" style="font-size:15px;"></i></a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);

                    var oldId = $(this).attr('id');
                    var newId = oldId.replace(suffix, (parseInt(suffix) + 1));
                    $(this).attr('id', newId);

                    //Replaced value
                    var type = $(this).attr('type');
                    if (type == "text") {
                        $(this).val('');
                    }
                    // If you have another Type then replace withF default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });


            $("#btnSubmit").submit(function (e) {
                serializeTableRow();
            });
        });

        function serializeTableRow() {
            var i = 0;
            $("body #tblProducer tr#dataRow").each(function (e) {

                $(this).find('input,select').each(function () {

                    // var suffix = $(this).find(':input:first').attr('name').match(/\d+/);
                    var oldN = $(this).attr('name');
                    var oldNIndex = oldN.match(/\d+/);
                    var newN = oldN.replace('[' + oldNIndex + ']', '[' + parseInt(i) + ']');
                    $(this).attr('name', newN);
                });
                i = (parseInt(i) + 1);
            });

            var j = 0;
            $("body #tblArtist tr#dataRow").each(function (e) {
                $(this).find('input,select').each(function () {

                    // var suffix = $(this).find(':input:first').attr('name').match(/\d+/);
                    var oldN = $(this).attr('name');
                    var oldNIndex = oldN.match(/\d+/);
                    var newN = oldN.replace('[' + oldNIndex + ']', '[' + parseInt(j) + ']');
                    $(this).attr('name', newN);
                });
                j = (parseInt(j) + 1);
            });
        }

    </script>
}

coursework02/Views/Albums/Create.cshtml
@model coursework02.ViewModels.AlbumVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Albums</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
       <label class="control-label col-md-2" >Cover Image</label>
        <div class="col-md-10">
            <input type="file" name="CoverImage" class="form-control" />
           
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Producer</label>

        <div class="col-md-10">

            @Html.ListBoxFor(x => x.ProducerIds, Model.Producers, new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.Producers, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Artist</label>

        <div class="col-md-10">
            @Html.ListBoxFor(x => x.ArtistIds, Model.ArtistList, new { @class = "form-control" })
            @*@Html.DropDownListFor(m => m.ArtistIds, new SelectList(ViewBag.Artists, "Text", "Value"), null, new { @class = "form-control", multiple = "multiple" })*@
            @Html.ValidationMessageFor(model => model.ArtistIds, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

coursework02/Views/Albums/Delete.cshtml
@model coursework02.Models.Albums

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Albums</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoverImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

coursework02/Views/Albums/Details.cshtml
@model coursework02.Models.Albums

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Albums</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoverImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverImagePath)
        </dd>  <dt>
            @Html.DisplayNameFor(model => model.IsAgeBar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAgeBar)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

coursework02/Views/Albums/Edit.cshtml
@model coursework02.Models.Albums

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Albums</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoverImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoverImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoverImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}